#!/usr/bin/env bash

# Install nginx on your web-01

echo -e "updating and instalation of Nginx\n"
sudo apt-get update -y -qq
sudo apt-get install nginx -y

echo -e "setting up staff\n"

# starting nginx service
sudo service nginx start

#allowing nginx on firewall
sudo ufw allow "Nginx HTTP"

#giving user easy time and ownership to files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R 755 /var/www

#backing up the default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

#creation of new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

#restart nginx
sudo service nginx restart

echo -e "\nComplete ✅ \n"
