#!/usr/bin/env bash
#Install nginx on your web-01
#Bash script that configures a new Ubuntu
#machine to respect above requirements
#(this script will be run on the server itself)

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo 'Hello World' > var/www/html/index.nginx-debian.html
sudo service nginx start
