#!/usr/bin/env bash
#Install nginx on your web-01
#Bash script that configures a new Ubuntu
#machine to respect above requirements
#(this script will be run on the server itself)

echo -e "Updating and installing Nginx. \n"
sudo apr-get update -y -qq && \
	sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo service nginx restart

echo -e "\ncompleted. ✅\n"
