#!/usr/bin/env bash
# Script to configure a brand new Ubuntu machine

# Update and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

sudo mkdir /etc/nginx/html
sudo touch /var/www/html/index.html
echo "Hello World" | sudo tee /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx
sudo bash -c "cat > /etc/nginx/sites-available/default" <<EOF
server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-served-By \$HOSTNAME;
    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Restarting Nginx
sudo systemctl restart nginx
