#!/usr/bin/env bash
# Script to configure a brand new ubuntu machine

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i 'listen 80 default_server;/a add_header X-served-By $hostname;' /etc/nginx/sites-available/default
service nginx start
