#!/usr/bin/env bash
# Script to configure a brand new ubuntu machine

apt-get -y update
apt-get -y install nginx

string="http {\n\tadd_header X-served-By \"$HOSTNAME\";"
sudo sed -i "s/http {http {/$string/" /etc/nginx/nginx.conf
# restarting nginx
sudo service nginx restart
