#!/usr/bin/env bash
#script that stops 4-to_infinity_and_beyond process

#program PID
ps aux | grep  "4-to_infinity_and_beyond"

#infinate process termination
if [ -n "$id" ]
then
  kill -15 "$id"
fi
