#!/usr/bin/env bash
#script that stops 4-to_infinity_and_beyond process

#program PID
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

#infinate process termination
if [ -n "$id" ]
then
  kill -15 "$id"
fi
