#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet

sudo pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 777 /etc/nginx/nginx.conf
sleep 2
sudo -u nginx nginx
